[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Chimera_Buster"
version = "1.2.0"
authors = [
  { name="Jessica Lauren Albert", email="jessica.albert2001@gmail.com" },
]
description = "eliminates chimeric reads by comparing the UMI sequences and finding any matches in the 5 prime or 3 prime UMIs and keeping the sequence that has the highest prevalence"
readme = "README.md"
license = {file = "LICENSE.txt"}
keywords = ["HIV", "UMIs", "PCR", "chimeras", "ONT sequencing"]	
requires-python = ">=3"
classifiers = [
	"Programming Language :: Python :: 3",
   	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent",
]

[project.scripts]
Chimera_Buster = "Chimera_buster.CLI_chimera_buster:main"

[project.urls]
Homepage = "https://github.com/JessicaA2019/Chimera_Buster"
