[tool.poetry]
name = "SimplesAPI"
version = "0.0.0-alpha.12"
description = "SimplesAPI is intended to be the easiest API to implementation in Python"
authors = ["Anderson Magalhaes <andersonmagalhaes.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
asyncpg = "^0.29.0"
databases = "^0.9.0"
sqlalchemy = "^2.0.30"
redis = "^5.0.6"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
