[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "no_nonsense"
version = "0.0.3"
authors = [
  { name="Hemil Ruparel", email="hemilruparel2002@gmail.com" },
]
description = "No nonsense is a static site generator."
readme = "Readme.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
]
dependencies = [
    "ruamel.yaml==0.18.6",
    "ruamel.yaml.clib==0.2.8",
    "wheezy.template==3.2.2",
]

[project.scripts]
no_nonsense = "no_nonsense:main_cli"

[project.urls]
Homepage = "https://gitlab.com/rahem027/no_nonsense"
Issues = "https://gitlab.com/rahem027/no_nonsense/-/issues"

[tool.hatch.build.targets.sdist]
exclude = [
  "dist",
  "example",
]