[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "SimpleQAgents"
version = "1.0.5"
authors = [
	{name = "Sergio", email = "asimplethings.ast@gmail.com"}
]
description = "Simple deep q agents for gymnasium environments"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
	"Programming Language :: Python :: 3",
	"License :: OSI Approved :: MIT License",
	"Operating System :: OS Independent"
]
dependencies = [
	"tensorflow>=2.16.1",
	"numpy>=1.26.3"
]
