[tool.poetry]
name = "evo-package-openai"
version = "2024.6.191633"
description = "evo-package-openai python"
authors = ["cyborg-ai-git <129898917+cyborg-ai-git@users.noreply.github.com>"]
readme = "README.md"
license = "CC BY-NC-ND 4.0"
include = ["LICENSE.txt"]

[tool.poetry.dependencies]
python = "^3.10"
evo-framework = "^2024.5.28"
openai =  "^1.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
