[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cbz_generator"
version = "0.0.1"
authors = [
  { name="Tyler Crosby", email="contact@tycro.io" },
]
description = "Utility for converting images into a CBZ archive individually or in bulk."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/croozelberryTea/cbz-generator"
Issues = "https://github.com/croozelberryTea/cbz-generator/issues"