[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rpis_lib"
version = "0.0.7"
authors = [
    { name = "jaanonim" },
]
description = "Library for Statistic and Probability written for collage course."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "scipy>=1.13.1"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

