[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry]
name = "gester"
version = "1.3.6"
description = "A game engine for console based text game"
readme = "README.md"
keywords = ["games", "game development", "game engine", "text-game-engine", "console game engine"]
license = "BSL-1.0"
authors = ["John Anchery <john.anchery@mail.ru>"]
repository = "https://github.com/etcetra7n/gest"

classifiers = [
    "Topic :: Games/Entertainment",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.3",
    "Programming Language :: Python :: 3.4",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: Boost Software License 1.0 (BSL-1.0)",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment"
    ]

[tool.poetry.scripts]
gest = 'gester.gest:main'

[tool.poetry.extras]
pygame = ["pygame"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/etcetra7n/gest/issues"
"Repository" = "https://github.com/etcetra7n/gest"
