[tool.poetry]
name = "yundownload"
version = "0.1.12"
description = "The downloader will automatically select the download mode < stream download/fragment download >"
authors = ["yunhai <bybxbwg@foxmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
